### ISSUE TITLE
Inability to craft blocks of gem back to gems

### ISSUE THREAD

**Issue by Greg-21** [Coliwogg/Gems-And-Crystals#9]
When you craft blocks of ruby, sapphire, topaz, and amethyst (e.g. to save a bit of chest space), and then you decide to get the materials back, you will notice that it can't be done.

For comparison, in Gems and Crystals mod for Minecraft 1.15 and even the one for 1.14 those blocks work as they should, as well as the vanilla Minecraft emeralds and blocks of emerald.

Screenshot showing this issue:
![Blocks-of-gem-cant-be-crafted-back-to-gems](https://user-images.githubusercontent.com/34160838/80975654-abc3f580-8e22-11ea-87e4-fdeb5697d596.png)

I was able to reproduce this issue on the following configurations (I didn't test other configs for Minecraft 1.12.2):
* Minecraft version: 1.12.2
* Gems and Crystals versions: 1.2.7.1, 1.1.3
* Forge versions: 14.23.5.2847, 14.23.5.2768

**Comment by Coliwogg** [comment]
This issue should be fixed in the new version Gems and Crystals-1.12.2-1.2.7.2.
Thanks for bringing this to my attention!

**Comment by Greg-21** [comment]
I'm glad to hear that :)

**Comment by Greg-21** [comment]
@Coliwogg, unfortuantely this issue came back with version 1.2.7.3 of this mod.
